### ISSUE TITLE
🐛 VSCode Extension not discovering correct Rome path

### ISSUE THREAD

**Issue by iOnline247** [rome/tools#1039] opened 2020-08-12 03:54 UTC
## Environment

```
$ rome rage --summary
```

<details>
<summary>Summary</summary>

```
Object {
    COLORTERM: "truecolor"
    LANG: "en_US.UTF-8"
    PATH: "C:\\Users\\MatthewB\\Documents\\Github\\NodeJS-Boilerplate\\node_modules\\.bin;C:\\Program
    Files\\PowerShell\\7-preview;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Microsoft SQL
    Server\\130\\Tools\\Binn\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files (x86)\\Microsoft Emulator Manager\\1.0\\;C:\\Program
    Files\\ngrok;C:\\Users\\MatthewB\\AppData\\Roaming\\nvm;C:\\Program Files\\nodejs;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\PowerShell\\7-preview\\preview;C:\\Program
    Files\\Git\\cmd;C:\\Program Files\\PowerShell\\7\\;C:\\Program
    Files\\Docker\\Docker\\resources\\bin;C:\\ProgramData\\DockerDesktop\\version-bin;C:\\Users\\MatthewB\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\MatthewB\\AppData\\Roaming\\npm;C:\\    
    Users\\MatthewB\\AppData\\Local\\Programs\\Fiddler;C:\\Users\\MatthewB\\.dotnet\\tools;C:\\Users\\MatthewB\\AppData\\Local\\Programs\\Microsoft VS
    Code\\bin;C:\\Users\\MatthewB\\AppData\\Roaming\\nvm;C:\\Program Files\\nodejs;C:\\Users\\MatthewB\\AppData\\Local\\Microsoft\\WindowsApps"
    TERM_PROGRAM: "vscode"
  }

User Config
  unset

Rome Version
  10.0.3-beta

Node Version
  14.0.0

Platform
  win32 x64 10.0.19041

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 24
    columns: 197
    cursor: true
    hyperlinks: true
    isTTY: true
    unicode: false
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: "C:\\Users\\MatthewB\\Documents\\Github\\Boilerplate"
    realCwd: "C:\\Users\\MatthewB\\Documents\\Github\\Boilerplate"
    silent: false
  }

Server Status
  Object {
    projects: Array [
      Object {id: 0}
      Object {id: 1}
    ]
    server: Object {
      heapTotal: 26_079_232
      pid: 16_776
      uptime: 0.356969299
    }
    workers: Array [
      Object {
        astCacheSize: 0
        heapTotal: 26_079_232
        ownedBytes: 0
        ownedFileCount: 0
        pid: 16_776
        uptime: 0.356722
      }
    ]
  }

Visual Studio Code
Version: 1.47.3 (system setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z (2 wks ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
```
</details>

## Steps To Reproduce

1. [Install VSCode extension](https://marketplace.visualstudio.com/items?itemName=rome.rome)

## Expected Results

I'd expect the Problems section to report what `$ npx rome check` does.

<details>
<summary>$ npx rome check</summary>

```
PS C:\Users\MatthewB\Documents\Github\Boilerplate> npx rome check

 .eslintrc.json:19:4 parse/json ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  × Comments aren't allowed in JSON

    17 │   "ignorePatterns": "dist/**/*",
    18 │   "rules": {
    19 │     // disable the rule for all files
    20 │     "@typescript-eslint/explicit-module-boundary-types": "off"

 tsconfig.json:8:4 parse/json ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  × Comments aren't allowed in JSON

    6 │     "charset": "utf8",
    7 │     "checkJs": true,
    8 │     // "declaration": true,
    9 │     "emitBOM": false,

 .devcontainer/devcontainer.json:1 parse/json ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  × Comments aren't allowed in JSON

  > 1 │ // For format details, see https://aka.ms/vscode-remote/devcontainer.json or this file's README at:
      │ ^
    2 │ // https://github.com/microsoft/vscode-dev-containers/tree/v0.128.0/containers/javascript-node-12
    3 │ {

 .vscode/extensions.json lint/pendingFixes  FIXABLE  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  × Pending formatting and safe fixes

     1  1 │   {
     2    │ - ··"recommendations":·[
     3    │ - ····"christian-kohler.npm-intellisense",
     4    │ - ····"coenraads.bracket-pair-colorizer",
     5    │ - ····"dbaeumer.vscode-eslint",
     6    │ - ····"esbenp.prettier-vscode",
     7    │ - ····"waderyan.nodejs-extension-pack"
     8    │ - ··]
        2 │ + → "recommendations":·[
        3 │ + → → "christian-kohler.npm-intellisense",
        4 │ + → → "coenraads.bracket-pair-colorizer",
        5 │ + → → "dbaeumer.vscode-eslint",
        6 │ + → → "esbenp.prettier-vscode",
        7 │ + → → "waderyan.nodejs-extension-pack"
        8 │ + → ]
     9  9 │   }

  i To apply fixes and formatting run
  $ rome check .vscode/extensions.json --apply

 .vscode/launch.json:2:2 parse/json ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  × Comments aren't allowed in JSON

    1 │ {
    2 │   // Use IntelliSense to learn about possible attributes.
    3 │   // Hover to view descriptions of existing attributes.

 .vscode/settings.json lint/pendingFixes  FIXABLE  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  × Pending formatting and safe fixes

     1  1 │   {
     2    │ - ··"[javascript]":·{
     3    │ - ····"editor.defaultFormatter":·"esbenp.prettier-vscode"
     4    │ - ··},
     5    │ - ··"[json]":·{
     6    │ - ····"editor.defaultFormatter":·"esbenp.prettier-vscode"
     7    │ - ··},
     8    │ - ··"[markdown]":·{
     9    │ - ····"editor.formatOnSave":·true,
    10    │ - ····"editor.wordWrap":·"on",
    11    │ - ····"editor.renderWhitespace":·"all",
    12    │ - ····"editor.acceptSuggestionOnEnter":·"off"
    13    │ - ··},
    14    │ - ··"editor.cursorBlinking":·"blink",
    15    │ - ··"editor.cursorStyle":·"block",
    16    │ - ··"editor.defaultFormatter":·"esbenp.prettier-vscode",
    17    │ - ··"editor.formatOnPaste":·true,
    18    │ - ··"editor.formatOnSave":·true,
    19    │ - ··"editor.trimAutoWhitespace":·true,
    20    │ - ··"[jsonc]":·{
    21    │ - ····"editor.defaultFormatter":·"vscode.json-language-features"
    22    │ - ··}
        2 │ + → "[javascript]":·{
        3 │ + → → "editor.defaultFormatter":·"esbenp.prettier-vscode"
        4 │ + → },
        5 │ + → "[json]":·{
        6 │ + → → "editor.defaultFormatter":·"esbenp.prettier-vscode"
        7 │ + → },
        8 │ + → "[markdown]":·{
        9 │ + → → "editor.formatOnSave":·true,
       10 │ + → → "editor.wordWrap":·"on",
       11 │ + → → "editor.renderWhitespace":·"all",
       12 │ + → → "editor.acceptSuggestionOnEnter":·"off"
       13 │ + → },
       14 │ + → "editor.cursorBlinking":·"blink",
       15 │ + → "editor.cursorStyle":·"block",
       16 │ + → "editor.defaultFormatter":·"esbenp.prettier-vscode",
       17 │ + → "editor.formatOnPaste":·true,
       18 │ + → "editor.formatOnSave":·true,
       19 │ + → "editor.trimAutoWhitespace":·true,
       20 │ + → "[jsonc]":·{
       21 │ + → → "editor.defaultFormatter":·"vscode.json-language-features"
       22 │ + → }
    23 23 │   }

  i To apply fixes and formatting run
  $ rome check .vscode/settings.json --apply

 src/index.js:1 parse/js ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  × import and export can only appear in a module

  > 1 │ import { v4 as uuidv4 } from "uuid";
      │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2 │ import Logger from "./logger";

  i Change the extension to .mjs to turn this file into a module

  i Add "type": "module" to your package.json

 src/logger.js:2 parse/js ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  × import and export can only appear in a module

    1 │ /* eslint class-methods-use-this: ["error", { "exceptMethods": ["EVENTS"] }] */
  > 2 │ import Emittery from "emittery";
      │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    3 │ 
    4 │ const {

  i Change the extension to .mjs to turn this file into a module

  i Add "type": "module" to your package.json

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
i Fixes available. To apply safe fixes and formatting run
$ rome check --apply
i To choose fix suggestions run
$ rome check --review
× Found 8 problems
```
</details>

![image](https://user-images.githubusercontent.com/515152/89973123-96364700-dc2d-11ea-870f-6420c2fe19d5.png)

**Comment by sebmck** [comment] 2020-08-12 03:55
Most likely duplicate of #1028, also see #1001. It will be fixed in an upcoming release (<1 hour).

**Comment by iOnline247** [comment] 2020-08-12 17:27
This remains an issue for me after upgrading the this version: `"rome": "^10.0.4-beta"`
I should note, I'm using `rome` locally and didn't install it globally.

**Comment by yassere** [comment] 2020-08-12 18:01
What does it say in the Rome output channel in VS Code? Is it successfully discovering the path to Rome in `node_modules` and is it watching your project directory?

**Comment by iOnline247** [comment] 2020-08-12 19:41
This is from the Output window:
`No Rome path found. Waiting for workspace folder changes before trying again`

**Comment by yassere** [comment] 2020-08-12 20:19
Do you have Rome installed locally in your project directory? (i.e. `npm install rome` without a global flag)

If so, we'll need to figure out why the extension isn't finding it.

**Comment by iOnline247** [comment] 2020-08-13 02:40
Yes, I tried both versions from a local install: `"rome": "^10.0.3-beta"` & `"rome": "^10.0.4-beta"`.
Using npx works, but using VSCode after a `npx rome init` doesn't seem to work. I have *not* installed this globally to date.

**Comment by iOnline247** [comment] 2020-08-13 02:42
If there's a debug/verbose logging mode for the extension, I'll give it a shot. I don't mind spending the time getting this up and running, so let me know how I can get you more information to troubleshoot.

**Comment by yassere** [comment] 2020-08-14 23:43
Thanks for helping troubleshoot!

I don't think there's any extra logging that the extension can currently do while it's attempting to locate the Rome path.

Could you try adding a top-level field to your `package.json` called `romeLSPBin` with the relative path from your project directory to the `rome/index.js` in your `node_modules`?

**Comment by Shuunen** [comment] 2020-08-15 09:38
Same here 😢 

![image](https://user-images.githubusercontent.com/439158/90309765-92374d00-deeb-11ea-954d-af69a7807ced.png)

Rome check is reporting 3 problems, but VSCode with `rome.rome` extension does not : 

![image](https://user-images.githubusercontent.com/439158/90309785-bdba3780-deeb-11ea-8667-d351422c2922.png)

![image](https://user-images.githubusercontent.com/439158/90309789-c6127280-deeb-11ea-899c-05e2de9b5c1b.png)

Even with your suggestion @yassere 

![image](https://user-images.githubusercontent.com/439158/90309802-e5a99b00-deeb-11ea-8705-5a2bfb7ea377.png)

**Comment by sebmck** [comment] 2020-08-15 09:43
What errors are you expecting there to be visible? Keep in mind that we explicitly hide the "pending fixes and formatting" diagnostic as it's not useful in an editor and would be covered by auto formatting, the other diagnostic suggestions, and quick fixes.

**Comment by Shuunen** [comment] 2020-08-15 09:52
I'm expecting to see the 3 problems `rome check` found.

Here for example, I just run `rome check --apply` and one problem still exists : 

![image](https://user-images.githubusercontent.com/439158/90309935-366dc380-deed-11ea-873a-d9f9f6906d31.png)

Why all these are considered useless to show ? 

EsLint have warn & error severity levels and is well displayed in the VSCode problem tab because lint issues are sorted from error to warn.

**Comment by Shuunen** [comment] 2020-08-15 09:55
Can anyone provide a code snippet that should display errors in this VSCode problem tab to verify that extension is working properly ?

**Comment by sebmck** [comment] 2020-08-15 09:57
They aren't useless to show. I was referring specifically to a single sort of diagnostic we output that was included in the CLI output from the example in the issue body.

We need to add additional logging to the extension output channel so we can more properly debug these sorts of issues.

**Comment by Shuunen** [comment] 2020-08-15 10:00
Ok, let me know if I can help to investigate more.

I tried many folderpath & filepath for `"romeLSPBin"` and then reload my VSCode but I'm still seing `No Rome path found. Waiting for workspace folder changes before trying again` in the Rome extension output.

**Comment by ematipico** [comment] 2020-08-15 10:40
Is there a chance where you can share your project or a minimal repository where we can replicate the issue?

**Comment by Shuunen** [comment] 2020-08-15 12:35
[test-rome.zip](https://github.com/romefrontend/rome/files/5078632/test-rome.zip)

**Comment by yassere** [comment] 2020-08-15 12:55
@Shuunen Did you try "node_modules/rome/bin/rome/index.js" for `romeLSPBin`?

You shouldn't have to specify the path yourself, but I'm just trying to see if it works for troubleshooting purposes.

You won't see diagnostics from Rome under "Problems" if you see "No Rome path found" because that means the extension couldn't find the LSP server to even start it.

**Comment by Shuunen** [comment] 2020-08-15 14:52
Same result : 
![image](https://user-images.githubusercontent.com/439158/90314929-b446c480-df17-11ea-8d62-fcb028125bb5.png)

**Comment by iOnline247** [comment] 2020-09-04 00:54
I spent some time debugging this using ProcMon. I found some things of interest. The `NAME INVALID` errors have a file path prefix of: `C:\c:\`, which would cause problems. Hopefully, it helps. 
Also, should this issue be reopened?

![name invalid](https://user-images.githubusercontent.com/515152/92187338-73abde00-ee27-11ea-80f3-50b458de00ac.png)

**Comment by yassere** [comment] 2020-09-04 11:34
@iOnline247 Thanks for the help. That does look like a useful clue.

**Comment by iOnline247** [comment] 2020-12-16 09:25
Circling back on this... Any progress?
I could start a PR, but I'm not too sure where to look at in the code for sus out this bug. Can you give me some tips and I'll start poking around.

**Comment by ematipico** [comment] 2020-12-22 12:05
No news unfortunately :( most of us don't have a Windows OS, so it's difficult to triage the issue. Any help is welcome!

About where to look at:
- https://github.com/rome/tools/blob/main/internal/core/server/lsp/LSPServer.ts: this is where the bulk of the job happens
- https://github.com/rome/tools/blob/main/public-packages/vscode-extension/index.ts: this the VSCode extension, it doesn't do much other than sending instructions to the rome server

**Closed** 2021-01-14 16:22 UTC
Labels: bug: confirmed, help wanted, vscode
