### ISSUE TITLE
🐛 Segments were normalized to an empty array. Original: ["file:..",".."]

### ISSUE THREAD

**Issue by alappe** [rome/tools#1190] opened 2020-09-29 12:23 UTC
## Environment

```
$ npx rome rage --summary 2>&1 | pbcopy

Environment Variables
  Object {
    COLORTERM: "truecolor"
    LANG: "en_US.UTF-8"
    TERM: "screen-256color"
    TMUX: "/tmp//tmux-502/default,5752,3"
  }

User Config
  unset

Rome Version
  10.0.4-beta

Node Version
  12.18.3

Platform
  darwin x64 19.6.0

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 1
    columns: 100
    cursor: false
    hyperlinks: false
    isTTY: false
    unicode: false
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: "/Users/nd/src/myproj/apps/myproj/assets/js"
    realCwd: "/Users/nd/src/myproj/apps/myproj/assets/js"
    silent: false
  }

Server Status
  Object {
    projects: Array [
      Object {id: 0}
      Object {id: 1}
    ]
    server: Object {
      heapTotal: 27_680_768
      pid: 77_562
      uptime: 1.474552944
    }
    workers: Array [
      Object {
        astCacheSize: 0
        heapTotal: 27_680_768
        ownedBytes: 0
        ownedFileCount: 0
        pid: 77_562
        uptime: 1.474492295
      }
    ]
  }
```

## Steps To Reproduce

1. `npx rome init`, resulting in:

```

 project-rome/@internal/path/index.ts:823:8 internalError/request  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Segments were normalized to an empty array. Original: ["file:..",".."]

  10. ___R$$priv$project$rome$$internal$path$index_ts$parsePathSegments (project-rome/@internal/path/index.ts:823:8)
  11. ___R$project$rome$$internal$path$index_ts$createUnknownFilePath (project-rome/@internal/path/index.ts:932:16)
  12. ___R$project$rome$$internal$codec$js$manifest$dependencies_ts$parseDependencyPattern (project-rome/@internal/codec-js-manifest/dependencies.ts:469:2)
  13. ___R$project$rome$$internal$codec$js$manifest$dependencies_ts$normalizeDependencies (project-rome/@internal/codec-js-manifest/dependencies.ts:515:16)
  14. ___R$project$rome$$internal$codec$js$manifest$index_ts$normalizeManifest (project-rome/@internal/codec-js-manifest/index.ts:678:19)
  15. ___R$project$rome$$internal$core$server$fs$MemoryFileSystem_ts$default.declareManifestWithPossibleDiagnosticsThrow (project-rome/@internal/core/server/fs/MemoryFileSystem.ts:656:12)
  16. ___R$project$rome$$internal$diagnostics$wrap_ts$catchDiagnostics (project-rome/@internal/diagnostics/wrap.ts:29:16)
  17. ___R$project$rome$$internal$core$server$fs$MemoryFileSystem_ts$default.declareManifest (project-rome/@internal/core/server/fs/MemoryFileSystem.ts:627:24)
  18. ___R$project$rome$$internal$core$server$fs$MemoryFileSystem_ts$default.addFile (project-rome/@internal/core/server/fs/MemoryFileSystem.ts:926:3)
  19. declareItem (project-rome/@internal/core/server/fs/MemoryFileSystem.ts:760:4)
  20. ___R$project$rome$$internal$core$server$fs$MemoryFileSystem_ts$default.addDirectory (project-rome/@internal/core/server/fs/MemoryFileSystem.ts:771:5)
  21. declareItem (project-rome/@internal/core/server/fs/MemoryFileSystem.ts:762:4)
  22. Function.all
  23. ___R$project$rome$$internal$core$server$fs$MemoryFileSystem_ts$default.addDirectory (project-rome/@internal/core/server/fs/MemoryFileSystem.ts:777:2)
  24. declareItem (project-rome/@internal/core/server/fs/MemoryFileSystem.ts:762:4)
  25. Function.all
  26. ___R$project$rome$$internal$core$server$fs$MemoryFileSystem_ts$default.addDirectory (project-rome/@internal/core/server/fs/MemoryFileSystem.ts:777:2)
  27. declareItem (project-rome/@internal/core/server/fs/MemoryFileSystem.ts:762:4)
  28. Function.all
  29. ___R$project$rome$$internal$core$server$fs$MemoryFileSystem_ts$default.addDirectory (project-rome/@internal/core/server/fs/MemoryFileSystem.ts:777:2)
  and 9 others...

  ⚠ This diagnostic was derived from an internal Rome error. Potential bug, please report if necessary.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✖ Found 1 problem
```

## Expected Results

I expected it to generate a config and let me explore the power of rome.

**Comment by ematipico** [comment] 2020-09-29 14:44
Hi @alappe , thank you for filing the issue!

Can you share your `package.json`? If possible. It might help to triage the issue

**Comment by alappe** [comment] 2020-09-29 14:48
@ematipico Sure:

```
{
  "repository": {},
  "description": " ",
  "license": "MIT",
  "scripts": {
    "deploy": "webpack --mode production",
    "watch": "webpack --mode development --watch"
  },
  "dependencies": {
    "phoenix": "file:../../../deps/phoenix",
    "phoenix_html": "file:../../../deps/phoenix_html",
    "phoenix_live_view": "file:../../../deps/phoenix_live_view",
    "nprogress": "^0.2.0",
    "d3-selection": "^2.0.0",
    "d3-scale": "^3.2.2",
    "d3-shape": "^2.0.0",
    "d3-array": "^2.7.1",
    "d3-transition": "^2.0.0",
    "d3-ease": "^2.0.0",
    "d3-axis": "^2.0.0",
    "date-fns": "^2.16.1"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "babel-loader": "^8.0.0",
    "copy-webpack-plugin": "^5.1.1",
    "css-loader": "^3.4.2",
    "file-loader": "^6.1.0",
    "mini-css-extract-plugin": "^0.9.0",
    "node-sass": "^4.13.1",
    "optimize-css-assets-webpack-plugin": "^5.0.1",
    "sass-loader": "^8.0.2",
    "terser-webpack-plugin": "^2.3.2",
    "webpack": "4.41.5",
    "webpack-cli": "^3.3.2"
  }
}
```

The local packages do exist and webpack builds the project without complaints. Happy to provide more information…

**Comment by ematipico** [comment] 2020-09-29 14:57
As I thought, the issue is with local paths `"file:../../"` that Rome probably doesn't know how to handle. Thank you for providing these information!

**Comment by koriolis** [comment] 2020-10-19 09:32
Hi. Just to add a little information that might be useful. I got the exact same problem/error and my `package.json` doesn't have any local paths defined.
Suspecting - for some reason - that it might be a conflict with an installed package, I triaged every single package on my setup on an empty folder, removing them one by one and doing a fresh install followed by `npx rome init`.
In my case a dev dependency package that I had installed induced this error: [Depcheck](https://github.com/depcheck/depcheck)

Hope the information helps somewhat.

**Comment by sebmck** [comment] 2020-11-13 20:52
This should be fixed in `main`.

**Closed by sebmck** 2020-11-13 20:52 UTC
Labels: bug: confirmed

**Comment by Andrew-Dyachenko** [comment] 2020-12-28 11:52
I got the same problem with `"rome": "^10.0.4-beta"` :neutral_face:
The error occurs at the first start with `yarn rome init` command at the project directory

**Screenshot**

![Снимок экрана 2020-12-28 в 14 31 00](https://user-images.githubusercontent.com/10127643/103211744-0d892080-491a-11eb-8e5f-bf949d76407b.png)

**package.json**

```json{
	"name": "someProject",
	"version": "0.1.0",
	"private": true,
	"scripts": {
		"serve": "vue-cli-service serve",
		"bd": "node build",
		"build": "vue-cli-service build --no-clean",
		"lint": "vue-cli-service lint",
		"test:unit": "vue-cli-service test:unit",
		"excel": "node i18n-processor.js"
	},
	"dependencies": {
		"axios": "^0.19.2",
		"babel-polyfill": "^6.26.0",
		"clipboard": "^2.0.4",
		"core-js": "^2.6.5",
		"date-fns": "^1.30.1",
		"dayjs": "^1.8.17",
		"echarts": "^4.2.1",
		"element-ui": "^2.10.1",
		"fs-path": "0.0.24",
		"inquirer": "^6.5.0",
		"moment": "^2.24.0",
		"nprogress": "^0.2.0",
		"register-service-worker": "^1.6.2",
		"shelljs": "^0.8.3",
		"ts-loader": "^7.0.5",
		"tslint": "^6.1.2",
		"vue": "^2.6.10",
		"vue-awesome-swiper": "^3.1.3",
		"vue-class-component": "^7.2.3",
		"vue-i18n": "^8.11.2",
		"vue-property-decorator": "^9.0.0",
		"vue-qr": "^2.2.1",
		"vue-router": "^3.0.3",
		"vuex": "^3.0.1",
		"xlsx": "^0.15.1"
	},
	"devDependencies": {
		"@vue/cli-plugin-babel": "^3.8.0",
		"@vue/cli-plugin-eslint": "^3.8.0",
		"@vue/cli-plugin-pwa": "^3.8.0",
		"@vue/cli-plugin-typescript": "^3.8.0",
		"@vue/cli-plugin-unit-jest": "^3.8.0",
		"@vue/cli-service": "^3.8.0",
		"@vue/eslint-config-standard": "^4.0.0",
		"@vue/test-utils": "1.0.0-beta.29",
		"babel-core": "7.0.0-bridge.0",
		"babel-eslint": "^10.0.1",
		"babel-jest": "^23.6.0",
		"babel-plugin-component": "^1.1.1",
		"eslint": "^5.16.0",
		"eslint-plugin-vue": "^5.0.0",
		"node-sass": "4.14.1",
		"rimraf": "^2.6.3",
		"rome": "^10.0.4-beta",
		"sass-loader": "^7.1.0",
		"typescript": "3.5.3",
		"vue-qr": "^2.2.1",
		"vue-template-compiler": "^2.6.10"
	},
	"eslintConfig": {
		"root": true,
		"env": {
			"node": true
		},
		"extends": ["plugin:vue/essential"],
		"rules": {},
		"parserOptions": {
			"parser": "babel-eslint"
		}
	},
	"postcss": {
		"plugins": {
			"autoprefixer": {}
		}
	},
	"browserslist": ["> 1%", "last 2 versions"],
	"jest": {
		"moduleFileExtensions": ["js", "jsx", "json", "vue"],
		"transform": {
			"^.+\\.vue$": "vue-jest",
			".+\\.(css|styl|less|sass|scss|svg|png|jpg|ttf|woff|woff2)$": "jest-transform-stub",
			"^.+\\.jsx?$": "babel-jest"
		},
		"transformIgnorePatterns": ["/node_modules/"],
		"moduleNameMapper": {
			"^@/(.*)$": "<rootDir>/src/$1"
		},
		"snapshotSerializers": ["jest-serializer-vue"],
		"testMatch": [
			"**/tests/unit/**/*.spec.(js|jsx|ts|tsx)|**/__tests__/*.(js|jsx|ts|tsx)"
		],
		"testURL": "http://localhost/",
		"watchPlugins": [
			"jest-watch-typeahead/filename",
			"jest-watch-typeahead/testname"
		]
	}
}
```

**Spoiler:**

```bash
MacBook-Pro-Andrey:someProject andrew$ yarn rome init
yarn run v1.19.0
$ /Users/andrew/Sites/someProject/node_modules/.bin/rome init

 project-rome/@internal/path/index.ts:823:8 internalError/request  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Segments were normalized to an empty array. Original: ["file:..",".."]

   7. ___R$$priv$project$rome$$internal$path$index_ts$parsePathSegments (project-rome/@internal/path/index.ts:823:8)
   8. ___R$project$rome$$internal$path$index_ts$createUnknownFilePath (project-rome/@internal/path/index.ts:932:16)
   9. ___R$project$rome$$internal$codec$js$manifest$dependencies_ts$parseDependencyPattern (project-rome/@internal/codec-js-manifest/dependencies.ts:469:2)
  10. ___R$project$rome$$internal$codec$js$manifest$dependencies_ts$normalizeDependencies (project-rome/@internal/codec-js-manifest/dependencies.ts:515:16)
  11. ___R$project$rome$$internal$codec$js$manifest$index_ts$normalizeManifest (project-rome/@internal/codec-js-manifest/index.ts:678:19)
  12. ___R$project$rome$$internal$core$server$fs$MemoryFileSystem_ts$default.declareManifestWithPossibleDiagnosticsThrow (project-rome/@internal/core/server/fs/MemoryFileSystem.ts:656:12)
  13. ___R$project$rome$$internal$diagnostics$wrap_ts$catchDiagnostics (project-rome/@internal/diagnostics/wrap.ts:29:16)
  14. ___R$project$rome$$internal$core$server$fs$MemoryFileSystem_ts$default.declareManifest (project-rome/@internal/core/server/fs/MemoryFileSystem.ts:627:24)
  15. ___R$project$rome$$internal$core$server$fs$MemoryFileSystem_ts$default.addFile (project-rome/@internal/core/server/fs/MemoryFileSystem.ts:926:3)
  16. declareItem (project-rome/@internal/core/server/fs/MemoryFileSystem.ts:760:4)
  17. ___R$project$rome$$internal$core$server$fs$MemoryFileSystem_ts$default.addDirectory (project-rome/@internal/core/server/fs/MemoryFileSystem.ts:771:5)
  18. declareItem (project-rome/@internal/core/server/fs/MemoryFileSystem.ts:762:4)
  19. Function.all
  20. ___R$project$rome$$internal$core$server$fs$MemoryFileSystem_ts$default.addDirectory (project-rome/@internal/core/server/fs/MemoryFileSystem.ts:777:2)
  21. declareItem (project-rome/@internal/core/server/fs/MemoryFileSystem.ts:762:4)
  22. Function.all
  23. ___R$project$rome$$internal$core$server$fs$MemoryFileSystem_ts$default.addDirectory (project-rome/@internal/core/server/fs/MemoryFileSystem.ts:777:2)
  24. ___R$project$rome$$internal$core$server$fs$MemoryFileSystem_ts$default.createWatcher (project-rome/@internal/core/server/fs/MemoryFileSystem.ts:297:3)
  25. ___R$project$rome$$internal$core$server$fs$MemoryFileSystem_ts$default.watch (project-rome/@internal/core/server/fs/MemoryFileSystem.ts:537:23)
  26. ___R$project$rome$$internal$core$server$project$ProjectManager_ts$default.findProject (project-rome/@internal/core/server/project/ProjectManager.ts:891:5)
  and 6 others...

  ⚠ This diagnostic was derived from an internal Rome error. Potential bug, please report if necessary.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✖ Found 1 problem
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
MacBook-Pro-Andrey:someProject andrew$
```

**Comment by Andrew-Dyachenko** [comment] 2020-12-29 07:53
Could you please recheck this issue?

**Comment by ematipico** [comment] 2020-12-29 07:59
@Andrew-Dyachenko as Sebastian wrote, this  issue is fixed in the current branch `main` but not yet published. Once we publish a new version (no ETA unfortunately), it should fix your issue.

**Comment by Andrew-Dyachenko** [comment] 2020-12-30 10:08
I tried to build the release myself, until it works due to unmet dependencies. Posted this problem here: [#215](https://github.com/rome/tools/issues/215)
