### ISSUE TITLE
Parenthesize expressions

### ISSUE THREAD

**Issue by NicholasLYang** [rome/tools#2497] opened 2022-04-26 15:12 UTC
Prettier has various [heuristics](https://github.com/prettier/prettier/blob/a9de2a128cc8eea84ddd90efdc210378a894ab6b/src/language-js/needs-parens.js) for parenthesizing expressions. For instance, when formatting JSX expressions inside certain statements, prettier tends to [wrap them in parentheses](https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=false&jsx=true&sourceType=module#bABlAHQAIABhACAAPQAgADwAZABpAHYAIABjAGwAYQBzAHMATgBhAG0AZQA9ACIAYQByAHQAaQBjAGwAZQAiACAAaQBkAD0AIgBhAHIAdABpAGMAbABlACIAIAB3AGkAZAB0AGgAPQB7ADEAMAAwADAAfQAgAGgAZQBpAGcAaAB0AD0AewAxADAAMAAwAH0AIABvAG4ATQBvAHUAcwBlAEUAbgB0AGUAcgA9AHsAYwBvAG4AcwBvAGwAZQAuAGwAbwBnAH0AIAAvAD4A). We should implement this logic.

**Comment by ematipico** [comment] 2022-05-23 13:16
Closing, duplicate of https://github.com/rome/tools/issues/2449

**Closed by ematipico** 2022-05-23 13:16 UTC
