### ISSUE TITLE
🐛 noUnusedVariables incorrectly marks property destruction in interfaces

### ISSUE THREAD

**Issue by peter-goodfill** [rome/tools#3787] opened 2022-11-18 10:24 UTC
### Environment information

```block
CLI:
  Version:              10.0.1
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   linux

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               loaded
  Formatter disabled:   false
  Linter disabled:      false

Workspace:
  Open Documents:       0

Discovering running Rome servers...

Running Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ℹ The client isn't connected to any server but rage discovered this running Rome server.

Server:
  Version:              10.0.1
  Name:                 rome_lsp
  CPU Architecture:     x86_64
  OS:                   linux

Workspace:
  Open Documents:       0

Other Active Server Workspaces:

Workspace:
  Open Documents:       0
  Client Name:          Visual Studio Code
  Client Version:       1.73.1

Workspace:
  Open Documents:       16
  Client Name:          Visual Studio Code
  Client Version:       1.73.1
```

### What happened?

![image](https://user-images.githubusercontent.com/91760307/202679489-7b9a7e1c-bdb5-49b6-9dd8-37c5d85b7cc6.png)

^^ incorrectly marked as unused

### Expected result

Interfaces and types should not be subject of this rule at all

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by nstepien** [comment] 2022-11-18 10:56
Dupe of #3669?

**Closed** 2022-11-18 11:20 UTC
Labels: S-Bug: confirmed, A-linter, L-JavaScript
