### ISSUE TITLE
🐛 Request textDocument/codeAction failed.

### ISSUE THREAD

**Issue by dougg0k** [rome/tools#4136] opened 2023-01-03 17:21 UTC
### Environment

```
> pnpm rome rage .
CLI:
  Version:              11.0.0
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   linux

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               loaded
  Formatter disabled:   false
  Linter disabled:      false

Workspace:
  Open Documents:       0

Discovering running Rome servers...

Incompatible Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ℹ Rage discovered this running server using an incompatible version of Rome.

Server:
  Version:              <=10.0.0

Running Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ℹ The client isn't connected to any server but rage discovered this running Rome server.

Server:
  Version:              11.0.0
  Name:                 rome_lsp
  CPU Architecture:     x86_64
  OS:                   linux

Workspace:
  Open Documents:       0
```

### What happened?

Just got this from VScode rome output.

```
[cli-stdout] data 18
[cli] exit 0
Connecting to "/tmp/rome-socket-" ...
[Info  - 2:16:03 PM] Server initialized with PID: 1907599
[Error - 2:19:28 PM] Request textDocument/codeAction failed.
  Message: failed to access range Range { start: Position { line: 173, character: 48 }, end: Position { line: 173, character: 61 } } in document file:///project/src/services/auth.service.ts
  Code: -32603 
failed to access range Range { start: Position { line: 173, character: 48 }, end: Position { line: 173, character: 61 } } in document file:///project/src/services/auth.service.ts

Caused by:
    position Position { line: 173, character: 61 } is out of range
```

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by leops** [comment] 2023-01-04 10:05
Could you restore the "Environment" section from the issue template with the output of the `rome rage` command ? It may contain important information to help us debug the issue

**Comment by dougg0k** [comment] 2023-01-04 13:18
It contains too much data if the server are on. Not possible.

**Comment by ematipico** [comment] 2023-01-04 13:38
@dougg0k, you're free to remove the logs from the output - or keep the relevant ones, but we need that information to triage the issue. We need further info to be able to help fix the problem.

**Comment by dougg0k** [comment] 2023-01-04 13:43
Done

**Comment by dougg0k** [comment] 2023-01-06 22:27
I am not able to easily reproduce the issue, but this time, I got somewhere else. I use typescript in the project and there was an typescript error, as I was trying to fix the type error trying out some stuff and saving, the error appeared. 

Tried (possible type fix > saved > failed) around 2 to 3 times, before I got it right, and in between, the error appeared.

That's pretty much it.

**Comment by leops** [comment] 2023-01-09 15:44
This looks like an instance of the document content on the server side getting out of sync with the text buffer in the editor client, but unfortunately without the server logs it's difficult to understand the sequence of events that make this happen

**Comment by hwallis93** [comment] 2023-01-12 16:44
I am trialling Rome for my medium-large TypeScript project and unfortunately hit this frequently. I am (anecdotally) more likely to hit it when moving lines up and down, or when my PC is under load.

Where can I find the server logs?

**Comment by dougg0k** [comment] 2023-01-12 17:20
First you start the rome server with `rome start`and logs will appear with `rome rage .`

**Comment by ematipico** [comment] 2023-01-12 19:52
> I am trialling Rome for my medium-large TypeScript project and unfortunately hit this frequently. I am (anecdotally) more likely to hit it when moving lines up and down, or when my PC is under load.
> 
> Where can I find the server logs?
> 

They in the temporary folder of the OS, under a folder called `rome-logs`

**Comment by hwallis93** [comment] 2023-01-13 09:57
[server.log.2023-01-13-09.txt](https://github.com/rome/tools/files/10410321/server.log.2023-01-13-09.txt)
Repro'd this morning by opening my codebase in VS code and moving some lines around. Server log attached, error first hit on line 1256. I closed VS Code immediately after hitting it to keep the log small.

For future reference my logs were in C:\Users\<username>\AppData\Local\Temp\rome-logs

**Comment by hwallis93** [comment] 2023-02-06 09:42
Any update on this?

**Comment by TomerAtarScopio** [comment] 2023-04-03 12:25
I seem to be getting this issue mostly after interacting a bit with the code in the code diff split editor, also in a TypeScript project. When this reproduces it also sometimes seems to produce broken code when formatting on save - some text gets deleted, or content reverts in some parts to old file content
also once it reproduces it fails on any file it seems and on every caret move, can be mitigated by Reload Window action

**Comment by ematipico** [comment] 2023-04-03 12:32
Thank you for the input. It seems we still have synchronisation issues: the document we have in the LSP and the document we have in the workspace get out of sync somehow.

There are a few issues already around the same problem. We're looking into it.

**Comment by ematipico** [comment] 2023-04-07 16:26
Duplicate of https://github.com/rome/tools/issues/4338

**Closed by ematipico** 2023-04-07 16:26 UTC
Labels: S-Needs info
