### ISSUE TITLE
🐛 Internal Fatal Timeout on rome check

### ISSUE THREAD

**Issue by egtann** [rome/tools#1013] opened 2020-08-09 14:30 UTC
Running `rome check` results in internal fatal timeout errors and never completes the "Adding project" phase. As a result, this tool cannot be used in my project. There's many errors in the following form:

```
i Please open an issue with the details provided above if necessary
! Worker 4 has not responded for 21s seconds. It is unlikely to become responsive. Currently
  processing:
- lint x 1
  - Object {
      parseOptions: Object {}
      options: Object {
        applySafeFixes: true
        compilerOptions: undefined
        prefetchedModuleSignatures: Object {}
        save: false
      }
      ref: Object {
        manifest: 1
        project: 2
        real: "<REDACTED>/worker-css.js"
        relative: "<REDACTED>"
        remote: false
        uid: "<REDACTED>"
      }
    }
i Please open an issue with the details provided above if necessary

 worker 4 project-rome/@internal/core/server/WorkerManager.ts:289:6 internalError/fatal  INTERNAL
FATAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  × Did not respond for 21321ms and was checked 6 times

  1. <anonymous> (project-rome/@internal/core/server/WorkerManager.ts:289:6)
  2. Timeout.<anonymous> (project-rome/@internal/events/Bridge.ts:175:7)

  ! Rome exited as this error could not be handled and resulted in a fatal error. Please report if
    necessary.

 project-rome/@internal/events/Bridge.ts:348:20 internalError/request ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  × Connection died

  1. ___R$project$rome$$internal$core$common$bridges$WorkerBridge_ts$default.end (
     project-rome/@internal/events/Bridge.ts:348:20)
  2. ___R$project$rome$$internal$core$server$WorkerManager_ts$default.end (
     project-rome/@internal/core/server/WorkerManager.ts:106:11)
  3. ___R$project$rome$$internal$core$server$Server_ts$default.onFatalError (
     project-rome/@internal/core/server/Server.ts:335:21)
  4. onFatalError (project-rome/@internal/core/server/WorkerManager.ts:288:17)
  5. Timeout.<anonymous> (project-rome/@internal/events/Bridge.ts:175:7)

  i Error occurred while requesting lint for cmd/dashboard/assets/js/ace.js

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

× Found 1 problem
```

## Environment

```
$ rome rage --summary
Environment Variables
  Object {
    LANG: "en_US.UTF-8"
    PATH: "<REDACTED>"
    TERM: "screen"
    TERM_PROGRAM: "tmux"
    TMUX: "/tmp/tmux-1000/default,62263,0"
    USER: "<REDACTED>"
  }

User Config
  unset

Rome Version
  10.0.3-beta

Node Version
  12.16.1

Platform
  openbsd x64 6.7

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 1
    columns: 100
    cursor: false
    hyperlinks: false
    isTTY: false
    unicode: false
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: "<REDACTED>"
    realCwd: "<REDACTED>"
    silent: false
  }

Server Status
  Object {
    projects: Array [
      Object {id: 0}
      Object {id: 1}
    ]
    server: Object {
      heapTotal: 54_329_344
      pid: 30_804
      uptime: 0.609144649
    }
    workers: Array [
      Object {
        astCacheSize: 0
        heapTotal: 54_329_344
        ownedBytes: 0
        ownedFileCount: 0
        pid: 30_804
        uptime: 0.609075216
      }
    ]
  }
```

## Steps To Reproduce

1. `npm install -D rome`
2. `npx rome init`
3. `npx rome check`

## Expected Results

It to succeed without timeouts.

**Comment by sebmck** [comment] 2020-08-09 19:05
The issue is most likely in the parser. Our parser is recoverable and there are certain conditions that can trigger infinite loops. Is the problematic file something you can share?

**Comment by ematipico** [comment] 2021-03-15 17:00
@egtann  I am going to close this issue. Feel free to open a new one if you have more details.

**Closed by ematipico** 2021-03-15 17:00 UTC
Labels: bug: unconfirmed
