### ISSUE TITLE
🐛 Incorrect evaluation of unreachable code with try/catch

### ISSUE THREAD

**Issue by bkasten-rbi** [rome/tools#3749] opened 2022-11-15 16:56 UTC
### What happened?

when a try/catch has code after it, if the code inside the try has a return, rome thinks the ending is unreachable. However it is reachable in the case where the try throws and the catch allows control flow to pass through.

https://docs.rome.tools/playground/?code=YQBzAHkAbgBjACAAZgB1AG4AYwB0AGkAbwBuACAAZgBvAG8AKAApACAAewAKACAAIAB0AHIAeQAgAHsACgAgACAAIAAgAGMAbwBuAHMAbwBsAGUALgBsAG8AZwAoACcAYgBhAHIAJwApAAoAIAAgACAAIAByAGUAdAB1AHIAbgAgAGUAeAB0AGUAcgBuAGEAbABGAHUAbgBjAHQAaQBvAG4AKAApAAoAIAAgAH0AIABjAGEAdABjAGgAIAAoAGUAcgByAG8AcgApACAAewAKACAAIAAgACAAaQBmACAAKABlAHIAcgBvAHIAIABpAG4AcwB0AGEAbgBjAGUAbwBmACAARQByAHIAbwByACkAIAB7AAoAIAAgACAAIAAgACAAcgBlAHQAdQByAG4AIAAnAGYAbwBvACcACgAgACAAIAAgAH0ACgAgACAAfQAKACAAIABmAGkAbgBhAGwAbAB5ACAAewB9AAoAIAAgAGMAbwBuAHMAbwBsAGUALgBsAG8AZwAoACcAYgBhAHoAJwApAAoAfQAKAAoAZgB1AG4AYwB0AGkAbwBuACAAZQB4AHQAZQByAG4AYQBsAEYAdQBuAGMAdABpAG8AbgAoACkAIAB7AAoAIAAgAHQAaAByAG8AdwAgACcAaABpACcACgB9AA%3D%3D&typescript=false&jsx=false

### Expected result

The control flow should see that the ending code _is_ reachable in certain situations.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment] 2022-11-15 18:12
Duplicate of https://github.com/rome/tools/issues/3654

**Closed by ematipico** 2022-11-15 18:12 UTC
Labels: S-Bug: confirmed, A-linter
