### ISSUE TITLE
🐛 Mismatch between VS Code Extension and CLI

### ISSUE THREAD

**Issue by Marabyte** [rome/tools#3128] opened 2022-08-29 13:07 UTC
### Environment information

```bash
VS Code: 1.70.2
VS Code Rome extension: 0.12.0
Rome CLI: 0.8.0-next.ff4153b
MacOS: 12.5.1
```

### What happened?

This is the `rome.json` config file at my projects root:
```json
{
  "formatter": {
    "enabled": true
  },
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true
    }
  },
  "javascript": {
    "formatter": {
      "quoteStyle": "single"
    }
  }
}
```

When I run `npx rome format ./src --write` the files are successfully formatted:
-  Indentation style changes from `spaces` to `tabs`
- Quotes are from `single` instead of `double`

But if I edit a file, the quote style will revert to `double` on save.
These are the workspace settings:
```json
  "editor.formatOnSave": true,
  "[typescript]": {
    "editor.defaultFormatter": "rome.rome"
  },
```

The issue seems similar to https://github.com/rome/tools/issues/3088 so feel free to close this one if they overlap.

Edit:
Changing the logs to `verbose` I noticed an error
```
ERROR rome_lsp::server Couldn't load the configuration file, reason:
 Rome couldn't load the configuration file, here's why: 
missing field `globals` at line 15 column 3
```

I've added ` "globals": [],` to `rome.json` as suggested in this issue https://github.com/rome/tools/issues/2996 but the formatting mismatch still happens.
 
### Expected result

On save the formatting should be the same as running the CLI

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment] 2022-08-29 13:28
Probably a duplicate of https://github.com/rome/tools/issues/3088

I will look into it

**Closed** 2022-08-30 09:25 UTC
Labels: bug: confirmed, A-LSP, E-VScode
