### ISSUE TITLE
Config can't be updated when project doesn't lint

### ISSUE THREAD

**Issue by pikeas** [rome/tools#1149] opened 2020-08-25 22:47 UTC
On first-use in an existing project.

## Environment

```
$ rome rage --summary
Environment Variables
  Object {
    COLORFGBG: "0;15"
    COLORTERM: "truecolor"
    LANG: "en_US.UTF-8"
    TERM: "xterm-256color"
    TERM_PROGRAM: "iTerm.app"
  }

User Config
  unset

Rome Version
  10.0.4-beta

Node Version
  12.18.3

Platform
  darwin x64 19.6.0

Terminal Features
  Object {
    background: "light"
    colorDepth: 24
    columns: 197
    cursor: true
    hyperlinks: true
    isTTY: true
    unicode: true
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: "/Users/me/code/foo"
    realCwd: "/Users/me/code/foo"
    silent: false
  }

Server Status
  Object {
    projects: Array [
      Object {id: 0}
      Object {id: 1}
    ]
    server: Object {
      heapTotal: 26_320_896
      pid: 78_078
      uptime: 0.172710707
    }
    workers: Array [
      Object {
        astCacheSize: 0
        heapTotal: 26_320_896
        ownedBytes: 0
        ownedFileCount: 0
        pid: 78_078
        uptime: 0.172635536
      }
    ]
  }
```

## Steps To Reproduce

1. Have a directory which causes `projectManager/nameCollision` (potentially any lint error, this is the one I had due to the project structure being in flux)
2. Run `rome config push lint.ignore "[that directory]"`
3. Config isn't updated:

```
⚠ Error occured while validating new config. Your changes have not been saved. Listed locations are not accurate.
```

## Expected Results

Config is updated. 

Also, `rome config` with no arguments produces misleading output: `Unknown command config`

**Comment by ematipico** [comment] 2020-08-26 07:11
Hi @pikeas 

Is it possible for you to share the project or a minimal repo to reproduce the issue, please? 

This is not a lint error but a fatal error. As you may notice, the error category doesn't have `lint/` at the beginning of its name. 

I am not familiar with this path of the code but it looks like there are two packages with the same name. If you shared a minimal repo, I might be able to help!

**Comment by pikeas** [comment] 2020-08-26 19:57
Hi @ematipico,

I've just confirmed that the following will reproduce the error:

```
mkdir rome-test
cd rome-test/
echo -e '{\n"name": "foo"\n}' > package.json
mkdir -p tmp/foo.bak
cp package.json tmp/foo.bak/
yarn add -D rome
./node_modules/.bin/rome init
./node_modules/.bin/rome check
./node_modules/.bin/rome config push lint.ignore "tmp"
# Error occured while validating new config. Your changes have not been saved. Listed locations are not accurate.
```
Bonus: Rome's error message has a typo, `occured` should be `occurred`.

Basically, a tmp directory with some cruft. This particular repro is meant to simulate "I have an older downloaded copy of this project's package.json nested for reference ". It doesn't seem like Rome should block updating its config on an "invalid" directory structure.

**Comment by ematipico** [comment] 2021-06-25 11:22
I am not sure this is an actual bug. Rome throws a fatal error because there are two packages with the same name, which is not allowed at the moment. Even if you added `tmp` manually to the `lint` section, that won't fix the issue.

If you think that this case is really common among users, feel free to file a feature request (maybe via Discussions) where we can create a allow list of packages allowed to be duplicated inside a project.

**Closed by ematipico** 2021-06-25 11:22 UTC
Labels: bug: confirmed
