### ISSUE TITLE
🐛 `useTemplate` code action creates broken code

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3528] opened 2022-10-28 10:02 UTC
### Environment information

```bash
Used the branch `feature/promote-rules-v2`
```

### What happened?

The following code:

```js
    const stringifiedExpressions = expressions.map(
      (doc) =>
        "${" +
        printDocToString(doc, {
          ...options,
          printWidth: Number.POSITIVE_INFINITY,
          endOfLine: "lf",
        }).formatted +
        "}"
    );
```

Emits a code action that, when applied, emits this code:

```js
    const stringifiedExpressions = expressions.map(
      (doc) =>
        `${${printDocToString(doc, {
          ...options,
          printWidth: Number.POSITIVE_INFINITY,
          endOfLine: "lf",
        }).formatted}}`
    );
```

Which is an error

### Expected result

It should emit

```js
    const stringifiedExpressions = expressions.map(
      (doc) =>
        `\${${printDocToString(doc, {
          ...options,
          printWidth: Number.POSITIVE_INFINITY,
          endOfLine: "lf",
        }).formatted}}`
    );
```

I think 

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by MichaReiser** [comment] 2022-10-31 07:40
Duplicate of #3451

**Closed by MichaReiser** 2022-10-31 07:40 UTC
Labels: S-Bug: confirmed, A-linter
