### ISSUE TITLE
🐛 expected an identifier, an array pattern, or an object pattern but instead found '('

### ISSUE THREAD

**Issue by Newbie012** [rome/tools#3746] opened 2022-11-15 14:47 UTC
### Environment information

```block
CLI:
  Version:              10.0.1
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   linux

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               unset

Workspace:
  Open Documents:       0

Discovering running Rome servers...

Server:
  Status:               stopped
```

### What happened?

1. create a file called `geo_tz.d.ts`
2. write:

```typescript
declare module "geo-tz" {
    export default function (lat: number, lng: number): string[];
}
```

3. get an error:

```
    1 │ declare module "geo-tz" {
  > 2 │     export default function (lat: number, lng: number): string[];
      │                             ^
    3 │ }
    4 │ 
  
  ℹ Expected an identifier, an array pattern, or an object pattern here
  
    1 │ declare module "geo-tz" {
  > 2 │     export default function (lat: number, lng: number): string[];
      │                             ^
    3 │ }
    4 │ 
```

### Expected result

While it's fixable by specifying a name to the function (identifier),  it's still considered a valid TypeScript code. Thus, the formatter should not crash ([See playground](https://docs.rome.tools/playground/?code=ZABlAGMAbABhAHIAZQAgAG0AbwBkAHUAbABlACAAIgBnAGUAbwAtAHQAegAiACAAewAKACAAIAAgACAAZQB4AHAAbwByAHQAIABkAGUAZgBhAHUAbAB0ACAAZgB1AG4AYwB0AGkAbwBuACAAKABsAGEAdAA6ACAAbgB1AG0AYgBlAHIALAAgAGwAbgBnADoAIABuAHUAbQBiAGUAcgApADoAIABzAHQAcgBpAG4AZwBbAF0AOwAKAH0ACgA%3D)).

PS - The results are very impressive!
> Formatted 1731 files in 452ms

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by denbezrukov** [comment] 2022-11-15 14:57
it seems that it's related https://github.com/rome/tools/issues/3485

**Comment by ematipico** [comment] 2022-11-15 15:55
Closing, duplicate of #3485 

So we can keep track of one single issue :) Thank you @denbezrukov for your comment!

**Closed by ematipico** 2022-11-15 15:55 UTC
Labels: S-Bug: unconfirmed
