### ISSUE TITLE
🐛 VS Code extension fails to format on save for TypeScript files

### ISSUE THREAD

**Issue by tracker1** [rome/tools#4470] opened 2023-05-13 18:27 UTC
### Environment information

```block
Using VS Code Rome Extension version `v0.24.0`
```

### What happened?

1. Set `"rome.rome"` as default formatter for TypeScript and TypeScriptReact in VS Code.
2. Attempt to format from the code menu.

Results in an error message.

```
Extension 'Rome' is configured as formatter but it cannot format 'TypeScript' files
```

### Expected result

Expected the file to be (re)formatted according to Rome rul;es.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by jgentes** [comment] 2023-05-14 22:09
This also happens for `.tsx` files, of type `Typescript-JSX`

**Comment by ematipico** [comment] 2023-05-17 06:47
Thank you for reporting this. Would you be able to share some log?

They are in the temporary folder of the OS, under the folder `rome-logs`. Ideally just the logs of when you attempt to format a file .

**Comment by WesleyYue** [comment] 2023-06-24 06:39
>I figured out the issue - apparently this setting became enabled in one of your updates. I don't think I turned it on manually. When I turned it off, everything started working:

Same, except I do have a Rome config file in my repo, but maybe this is looking somewhere else.

**Comment by ematipico** [comment] 2023-06-24 09:08
Going to close it, it seems the issue is solved.

**Closed** 2023-06-24 09:08 UTC
Labels: S-Needs info
