### ISSUE TITLE
🐛 extension wrongly detects noDeadCode

### ISSUE THREAD

**Issue by sviridoff** [rome/tools#2919] opened 2022-07-22 20:01 UTC
### Environment information

```bash
node 16.16.0
rome 0.7.0-next.f6510d6
typescript 4.7.4
ext rome.rome v0.10.0
```

### What happened?

The vscode extension is unable to detect correctly unreachable code, issuing `This code is unreachable rome(noDeadCode)`.

It happens with the rome extension in VSCode, when I have `enableCodeActions` set to `true` in the settings.

![Screenshot from 2022-07-22 21-56-34](https://user-images.githubusercontent.com/22574/180517870-38e885cb-3fc7-4c7d-9757-eb2f28788d7d.png)

### Expected result

should not to show issue there. the code in the example is totally reachable

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by IWANABETHATGUY** [comment] 2022-07-23 02:01
Can't reproduce 
![image](https://user-images.githubusercontent.com/17974631/180586271-ab456a71-2e68-4e6c-98a4-50282c86f7e1.png)
## Source code
```js
export class B {
  b() {
    return 'b'
  }
  c() {
    return 'c'
  }
  d() {
    return 'd'
  }
}

try {

} catch(err) {
  err = 3;
}
```

**Comment by IWANABETHATGUY** [comment] 2022-07-23 02:03
Vscode settings:
![image](https://user-images.githubusercontent.com/17974631/180586315-4b2b61af-4b68-493c-9128-8741e895eda1.png)
![image](https://user-images.githubusercontent.com/17974631/180586325-d886d096-89ed-4075-b7cd-195aa936d905.png)
Only one diagnostic is expected.

**Comment by sviridoff** [comment] 2022-07-23 13:58
thanks a lot for check it so fast. I also dont have any issue when I run rome from cli, is why I think is something to do with the extension. I just uploaded an example of the project where you can see the issue, https://github.com/sviridoff/issue , please take a look if you see the same as I

**Comment by IWANABETHATGUY** [comment] 2022-07-23 14:12
It seems that you still use the old `rome_lsp`, rome language server.

**Comment by IWANABETHATGUY** [comment] 2022-07-23 14:22
https://github.com/rome/tools/releases/tag/lsp%2Fv0.10.0 try to reinstall the Rome vscode extension,  would fix your issues.
![image](https://user-images.githubusercontent.com/17974631/180609166-7a7f7e38-b54f-46bb-80ab-e647eb95c4a3.png)

**Comment by sviridoff** [comment] 2022-07-23 15:00
uninstalled as you suggested, and installed again the last vsix release, Im still having the problem. Im using linux, dont know if is something that happens only there

**Comment by IWANABETHATGUY** [comment] 2022-07-23 15:31
Download the corresponding platform vsix here, https://github.com/rome/tools/releases/tag/lsp%2Fv0.10.0
I Assume you use Linux-x64
1. then download https://github.com/rome/tools/releases/download/lsp%2Fv0.10.0/rome_lsp-linux-x64.vsix
2. mv you `.vsix` to a temp dir
3. change its extension using `mv rome_lsp-linux-x64.vsix rome_lsp-linux-x64.zip`
4. unzip rome_lsp-linux-x64.zip
5. you should get something like 
```bash
├── [Content_Types].xml
├── extension
│  ├── icon.png
│  ├── LICENSE.txt
│  ├── node_modules
│  ├── out
│  ├── package-lock.json
│  ├── package.json
│  ├── README.md
│  ├── rome_syntax_tree.tmGrammar.json
│  └── server
├── extension.vsixmanifest
└── rome_lsp-linux-x64.zip
```
6. cd extension/server
7. run `pwd`
8. put this line below  into your vscode `settings.json`
![image](https://user-images.githubusercontent.com/17974631/180611738-d215c358-2869-4fcb-be18-05427d4d7686.png)
```
"rome.lspBin": "<pwd>"
```
9. reload the vscode extension

**Comment by IWANABETHATGUY** [comment] 2022-07-23 15:35
@ematipico , maybe we need some way to auto-upgrade rome_lsp

**Comment by sviridoff** [comment] 2022-07-23 15:52
yes, when you commented about old lsp server, I already made the experiment, unpacking and including it by settings, I updated my repository with the change, and sadly it didnt work. I will make a test with the mac on monday at my job if it happens there too.

![Screenshot from 2022-07-23 17-47-01](https://user-images.githubusercontent.com/22574/180612587-1ee91e7b-59ee-43e0-985c-826bb504ba90.png)

**Comment by ematipico** [comment] 2022-07-24 08:22
Hi, thank you for reporting the issue!

This is a duplicate of https://github.com/rome/tools/issues/2869, which has been fixed already.

We haven't released a new version of the LSP, yet. We will next week, which will contain the fix. Is this issue blocking you?

**Comment by IWANABETHATGUY** [comment] 2022-07-24 08:48
> 

So that's why I can't reproduce this issue because I use the latest version I compile locally.

**Comment by sviridoff** [comment] 2022-07-25 07:38
thanks lot, got it. just to know, how do I compile lsp server by myself

**Comment by IWANABETHATGUY** [comment] 2022-07-25 07:40
> 

https://github.com/rome/tools/blob/main/CONTRIBUTING.md#getting-started

**Comment by ematipico** [comment] 2022-07-25 07:41
> thanks lot, got it. just to know, how do I compile lsp server by myself

Here you can find the instructions: https://github.com/rome/tools/blob/main/CONTRIBUTING.md#language-server-and-vs-code-extension-development

**Closed** 2022-07-25 07:41 UTC
Labels: bug: unconfirmed
