### ISSUE TITLE
🐛 Rome init missing argument

### ISSUE THREAD

**Issue by jer3m01** [rome/tools#1418] opened 2021-04-03 21:46 UTC
## Environment

```
$ rome rage --summary
Environment Variables
  {LANG: "C.UTF-8", TERM: "xterm-256color"}

User Config
  unset

Rome Version
  10.0.7-nightly.2021.2.10

Node Version
  15.11.0

Platform
  linux x64 4.4.0-19041-Microsoft

Terminal Features
  {
    background: "unknown"
    colorDepth: 8
    cursor: true
    hyperlinks: true
    isTTY: true
    progress: true
    unicode: true
    columns: OneIndexedNumber<472>
  }

Client Flags
  {
    clientName: "cli"
    silent: false
    cwd: AbsoluteFilePath</mnt/d/Webstorm/test/oui>
    realCwd: AbsoluteFilePath</mnt/d/Webstorm/test/oui>
  }

Server Status
  {
    projects: [{id: 0}, {id: 1}]
    workers: [{astCacheSize: 0, heapTotal: 32_452_608, ownedBytes: 0n, ownedFileCount: 0, pid: 1_117, uptime: 0.3663973}]
    server: {heapTotal: 32_452_608, pid: 1_117, uptime: 0.3665485}
  }

```

## Steps To Reproduce

1. Create an empty project
2. `yarn rome init`
![image](https://user-images.githubusercontent.com/33844379/113492299-c68d6700-94d6-11eb-8cf4-562f1e02e052.png)

## Expected Results
Same as rome@latest

**Comment by superhawk610** [comment] 2021-05-05 21:32
The issue appears to be caused by [this line](https://github.com/rome/tools/blob/main/internal/core/server/commands/init.ts#L99), which is asserting that 1 argument is passed when in fact no arguments should be passed (there's even a check for 0 arguments a few lines earlier). It looks like this is confusing arguments and flags.

I believe there's an additional issue with the client-side `init` command where it always reports that a project already exists, but I can open a separate issue once this is resolved.

**Comment by ematipico** [comment] 2021-05-08 14:03
> The issue appears to be caused by [this line](https://github.com/rome/tools/blob/main/internal/core/server/commands/init.ts?rgh-link-date=2021-05-05T21%3A32%3A11Z#L99), which is asserting that 1 argument is passed when in fact no arguments should be passed (there's even a check for 0 arguments a few lines earlier). It looks like this is confusing arguments and flags.
> 
> ```ts
> req.expectArgumentLength(1);
> ```
> 
> I believe there's an additional issue with the client-side `init` command where it always reports that a project already exists, but I can open a separate issue once this is resolved.

Actually, the argument is expected to be passed. One of the most recent refactors broke the passage of arguments between commands using the Rome server.

**Comment by jamiebuilds** [comment] 2021-05-18 20:14
@ematipico Are you sure that assertion is supposed to exist? Only a few lines before it checks that the argument length is `0` and the args don't appear to be used anywhere. Do you mean you expect `--cwd <path>` to exist? Or rather what argument do you expect there?

**Comment by ematipico** [comment] 2021-05-19 07:38
I must I have had a trip. 

```js
req.expectArgumentLength(1);
```

Is actually the culprit! Not sure why I recall it was working. My bad! I will make a PR, it's a quick fix.

**Comment by ematipico** [comment] 2021-05-26 07:08
This is now fixed on `master`

**Closed by ematipico** 2021-05-26 07:08 UTC
Labels: bug: unconfirmed, cli, regression
