### ISSUE TITLE
🐛 rome with nestjs

### ISSUE THREAD

**Issue by xiaoxintang** [rome/tools#4767] opened 2023-08-15 06:06 UTC
### Environment information

```block
CLI:
  Version:                      12.1.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  ROME_LOG_DIR:                 unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           "v16.20.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.6.12"

Rome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 true

Workspace:
  Open Documents:               0

Discovering running Rome servers...

Incompatible Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

i Rage discovered this running server using an incompatible version of Rome.

Server:
  Version:                      <=10.0.0
```

### What happened?

1.  disabled rome
![image](https://github.com/rome/tools/assets/24927686/fb05e572-88d3-43dd-923c-2e9744c45d98)

2. enable rome
![image](https://github.com/rome/tools/assets/24927686/06a216a8-5617-422b-999c-8ea04d926582)

```ts
import { Controller, Get, HttpStatus, Res } from "@nestjs/common";
import { AppService } from "./app.service";
import { Public } from "./auth/public.decorator";
import { Response } from 'express'

@Controller()
export class AppController {
	constructor(private readonly appService: AppService) { }
	@Public()
	@Get()
	getHello(@Res() res: Response) {
		res.status(HttpStatus.OK)
	}
}
```

### Expected result

it should not throw an error

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by Eji4h** [comment] 2023-08-15 07:33
Same too

**Comment by ematipico** [comment] 2023-08-15 08:14
Duplicate of https://github.com/rome/tools/issues/4540

**Closed by ematipico** 2023-08-15 08:14 UTC
Labels: S-To triage
