### ISSUE TITLE
🐛 @rometools/backend-jsonrpc has no exported members

### ISSUE THREAD

**Issue by nikolaxhristov** [rome/tools#3664] opened 2022-11-11 02:05 UTC
### Environment information

```block
CLI:
  Version:              10.0.1
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   windows

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               loaded
  Formatter disabled:   false
  Linter disabled:      false

Workspace:
  Open Documents:       0

Discovering running Rome servers...

Running Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

i The client isn't connected to any server but rage discovered this running Rome server.        

Server:
  Version:              10.0.1
  Name:                 rome_lsp
  CPU Architecture:     x86_64
  OS:                   windows

Workspace:
  Open Documents:       0

Other Active Server Workspaces:

Workspace:
  Open Documents:       3
  Client Name:          Visual Studio Code - Insiders
  Client Version:       1.74.0-insider

Rome Server Log:

! Please review the content of the log file before sharing it publicly as it may contain sensitive information:
  * Path names that may reveal your name, a project name, or the name of your employer.
  * Source code

├─20541392ms INFO rome_lsp::server Starting Rome Language Server...
```

### What happened?

After

```bash
npm i rome
npm i @rometools/js-api
npm i @rometools/backend-jsonrpc
```

I'm trying to run the `@rometools/js-api` with:

```ts
const rome = await Rome.create({
	backendKind: BackendKind.DAEMON,
});
```

But I'm getting:

```
Cannot find module 'node_modules\@rometools\backend-jsonrpc\dist\index.js'. Please verify that the package.json has a valid "main" entry
```

### Expected result

To be able to run the daemon.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by nikolaxhristov** [comment] 2022-11-11 06:30
Duplicate of #3653

**Comment by MichaReiser** [comment] 2022-11-11 07:16
Closing as it is a duplicate of #3653

**Closed by MichaReiser** 2022-11-11 07:16 UTC
Labels: S-Bug: unconfirmed
