### ISSUE TITLE
🐛 Extension Prevents "Rename Symbol" from working between files

### ISSUE THREAD

**Issue by ZachHaber** [rome/tools#3188] opened 2022-09-08 22:30 UTC
### Environment information

```bash
Extension version: 0.14.1
VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.19044
```
<details>
<summary>System Info (from VSCode's error reporter)</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.72GB (45.42GB free)|
|Process Argv|--crash-reporter-id e4ef971e-1bc8-4898-8110-c4ac3a2b7acf|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

### What happened?

1. Set up 2 `mjs` files in a folder
2. export `something` from one (non-default)
3. import that `something` from the 1st file
4. use `f2` symbol rename to rename the `something` to `somethingElse`
5. Observe that `something` in the second file was never renamed
6. Reset to end of step 3. Disable the Rome extension, and observe that step 4 does rename `something` in the second file.

This also fails in TS files with import/export, but not CommonJS files with module.exports.

`otherFile.mjs`
```mjs
export const funcToRename = {};
```
`mainFile.mjs`
```mjs
import { funcToRename } from "./otherFileJs.mjs";

funcToRename();
```

This happens with these two files and this setup with no package.json or anything. Just these two in a folder by themselves, same exact result if you rename them to `.ts`. Extension Bisection helped narrow down that the issue is from the Rome Extension.

### Expected result

When using Rename Symbol, all references to that symbol should be successfully renamed no matter if it's in a different file. It should behave akin to how it does without Rome enabled.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment] 2022-09-12 08:17
Probably duplicate of https://github.com/rome/tools/issues/3187

**Comment by leops** [comment] 2022-09-12 10:12
> Probably duplicate of #3187

I don't think it is related, I'd say the root cause for issue is that we don't support renaming symbols across files yet, and the renaming action provided by our extension is taking over from the default implementation provided by the TypeScript language server that does support cross-file renaming.

**Comment by ematipico** [comment] 2022-10-03 13:38
Thank you @leops 

I think for the time being, we should move this feature under an opt-in flag inside the VSCode extension, and add to the description of the flag that this feature works only on single files.

**Comment by MichaReiser** [comment] 2022-10-31 07:46
@xunilrj is this fixed by your latest changes to make rename an opt-in feature?

**Comment by ematipico** [comment] 2022-11-01 07:42
I can confirm that it's an opt-in feature now, and marked as experimental

**Closed by ematipico** 2022-11-01 07:42 UTC
Labels: E-VScode, A-Editors
