### ISSUE TITLE
🐛 `noUnusedVariables` doesn't seem to take decorators into account

### ISSUE THREAD

**Issue by Marcisbee** [rome/tools#3741] opened 2022-11-15 13:15 UTC
### Environment information

```block
CLI:
  Version:              10.0.0
  Color support:        true

Platform:
  CPU Architecture:     aarch64
  OS:                   macos

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               loaded
  Formatter disabled:   false
  Linter disabled:      false

Workspace:
  Open Documents:       0
```

### What happened?

So rome returns error for this code:
```tsx
import { Exome } from 'exome';

import { undoable } from './undo';

export class CommentStore extends Exome {
  constructor(public comment: string) {
    super();
  }

  @undoable()
  public setComment(comment: string) {
    this.comment = comment;
  }
}
```

```
  ⚠ This variable is unused.

    1 │ import { Exome } from 'exome';
    2 │
  > 3 │ import { undoable } from './undo';
      │          ^^^^^^^^
    4 │
    5 │ export class CommentStore extends Exome {
```

Even tho `undoable` is clearly used as a decorator.

### Expected result

It should not mark `undoable` as  unused variable.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment] 2022-11-15 15:43
Duplicate of https://github.com/rome/tools/issues/3197

**Closed by ematipico** 2022-11-15 15:43 UTC
Labels: S-Bug: unconfirmed
