### ISSUE TITLE
🐛 Rome 12.1.0 does not respect rules configuration

### ISSUE THREAD

**Issue by nstepien** [rome/tools#4488] opened 2023-05-16 10:53 UTC
### Environment information

```block
CLI:
  Version:                      12.1.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  ROME_LOG_DIR:                 unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           "v20.1.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/9.6.6"

Rome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 true

Workspace:
  Open Documents:               0

Discovering running Rome servers...

Running Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

i The client isn't connected to any server but rage discovered this running Rome server.

Server:
  Version:                      12.1.0
  Name:                         rome_lsp
  CPU Architecture:             x86_64
  OS:                           windows

Workspace:
  Open Documents:               0

Other Active Server Workspaces:

Workspace:
  Open Documents:               1
  Client Name:                  Visual Studio Code
  Client Version:               1.78.2

Rome Server Log:

! Please review the content of the log file before sharing it publicly as it may contain sensitive information:
  * Path names that may reveal your name, a project name, or the name of your employer.
  * Source code

< "Comment is too long" >
```

### What happened?

With this config:
```json
{
  "files": {
    "ignore": ["./coverage/**/*", "./dist/**/*", "./lib/**/*", "*.json"]
  },
  "linter": {
    "rules": {
      "recommended": false,
      "a11y": {},
      "complexity": {},
      "correctness": {},
      "performance": {},
      "security": {},
      "style": {},
      "suspicious": {}
    }
  }
}
```
ALl the recommended rules are enabled when I run `rome check .`, even though `recommended` is set to `false.

If I remove these lines then the rules do not get unexpectedly re-enabled:
```json
      "a11y": {},
      "complexity": {},
      "correctness": {},
      "performance": {},
      "security": {},
      "style": {},
      "suspicious": {}
```

### Expected result

The rules configuration should be respected as defiend.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by Conaclos** [comment] 2023-05-16 10:57
This is certainly related to #4479.

**Comment by ematipico** [comment] 2023-05-16 14:00
Duplicate of https://github.com/rome/tools/issues/4479

**Closed by ematipico** 2023-05-16 14:00 UTC
Labels: S-To triage
