### ISSUE TITLE
🐛 Analyzer: too many diagnostics for`js/noDeadCode`

### ISSUE THREAD

**Issue by Boshen** [rome/tools#2961] opened 2022-07-29 06:40 UTC
### Environment information

[Playground](https://play.rome.tools/?code=function+foo%28%29+%7B%0A++return%0A%0A++if+%28x%29+%7B%0A++++a%0A++%7D%0A%0A++bar%28%29%0A%0A++while%28y%29+%7B%7D%0A%0A++b%0A%7D&lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&sourceType=module&typescript=true&jsx=true#ZgB1AG4AYwB0AGkAbwBuACAAZgBvAG8AKAApACAAewAKACAAIAByAGUAdAB1AHIAbgAKAAoAIAAgAGkAZgAgACgAeAApACAAewAKACAAIAAgACAAYQAKACAAIAB9AAoACgAgACAAYgBhAHIAKAApAAoACgAgACAAdwBoAGkAbABlACgAeQApACAAewB9AAoACgAgACAAYgAKAH0A)

### What happened?

Given dead code separated by control blocks, it outputs every single node/identifier/statement as a separate diagnostic.

```
function foo() {
  return

  if (x) {
    a
  }

  bar()

  while(y) {}

  b
}
```

```
warning[[js/noDeadCode](https://rome.tools/docs/lint/rules/noDeadCode/)]: This code is unreachable
  ┌─ main.js:4:7
  │
2 │   return
  │   ------ This statement will return from the function ...
3 │ 
4 │   if (x) {
  │       - ... before it can reach this code

warning[[js/noDeadCode](https://rome.tools/docs/lint/rules/noDeadCode/)]: This code is unreachable
  ┌─ main.js:5:5
  │
2 │   return
  │   ------ This statement will return from the function ...
  ·
5 │     a
  │     - ... before it can reach this code

warning[[js/noDeadCode](https://rome.tools/docs/lint/rules/noDeadCode/)]: This code is unreachable
  ┌─ main.js:8:3
  │
2 │   return
  │   ------ This statement will return from the function ...
  ·
8 │   bar()
  │   ----- ... before it can reach this code

warning[[js/noDeadCode](https://rome.tools/docs/lint/rules/noDeadCode/)]: This code is unreachable
   ┌─ main.js:10:9
   │
 2 │   return
   │   ------ This statement will return from the function ...
   ·
10 │   while(y) {}
   │         - ... before it can reach this code

warning[[js/noDeadCode](https://rome.tools/docs/lint/rules/noDeadCode/)]: This code is unreachable
   ┌─ main.js:12:3
   │
 2 │   return
   │   ------ This statement will return from the function ...
   ·
12 │   b
   │   - ... before it can reach this code
```

### Expected result

Preferably a single diagnostic for a block of continuous statements.

Let me shamefully show the result of my implementation ...

![image](https://user-images.githubusercontent.com/1430279/181698675-74c58a0c-9c74-4c83-ada7-964723dc44c6.png)

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by IWANABETHATGUY** [comment] 2022-07-29 06:49
This is more likely a suggestion rather than a bug, @ematipico, what do you think? Do we need to add another issue type?

**Comment by ematipico** [comment] 2022-07-29 07:06
> This is more likely a suggestion rather than a bug, @ematipico, what do you think? Do we need to add another issue type?

For suggestions, we should use GitHub discussions. We have a "suggestions" category.

@Boshen 

While I might agree that the messaging can be verbose, I would argue that the counter proposal is too slim for Rome's standards. We pledge to always explain the reason of an error, trying to point to the source of the error.

**Comment by Boshen** [comment] 2022-07-29 07:22
It's actually not about the explanation. 

If you look closely, Rome is currently reporting a separate "before it can reach this code" for every single node/identifier/statement. My suggestion is to combine these into a single reporting span.

I found this from a real case [here in lodash](https://github.com/lodash/lodash/blob/master/test/utils.js#L460-L572), where we get a screenful of diagnostics ...

**Comment by leops** [comment] 2022-07-29 07:41
This is partially due to a technical limitation in the way the Language Server Protocol represents diagnostics: in order to mark code as "useless" in the editor we need to emit a diagnostic covering that range, but a single diagnostic may only cover one continuous range at once. So when multiple statement or expressions are marked as unreachable in a function, the `noDeadCode` rule will merge contiguous diagnostics but if two unreachable ranges do not immediately follow each other the rule needs to emit multiple diagnostics instead.
Now in this case I agree that the logical range of code that's unreachable is single unit covering everything after the return statement and we should try to improve the range merging algorithm to support this by propagating unreachable ranges to the outer node. This would need to be implemented on a per-node basis, but the corresponding logic for `JsWhileStatement` for instance would be that if both the test expression and the entire body are covered by an unreachable range, these two ranges get merged into a single one covering the entire while loop (and running this logic in a loop so this new range recursively gets merged with the unreachable range covering the rest of the function body)

**Comment by ematipico** [comment] 2022-09-08 12:47
@leops is there something we can do to close this possible bug? If not a bug, then we should just close it

**Comment by leops** [comment] 2022-09-08 13:00
> @leops is there something we can do to close this possible bug? If not a bug, then we should just close it

I tried to come up with a solution to this a few weeks ago, and I think it would require more time to finish it. I still think this is important though, given how much work is required to implement the solution I would probably re-qualify this from a bug to a missing feature

**Closed** 2022-10-06 09:00 UTC
Labels: wishlist, A-Diagnostic
