### ISSUE TITLE
📎 Implement ESLint rule `no-this-before-super` 

### ISSUE THREAD

**Issue by Conaclos** [rome/tools#3929] opened 2022-12-03 17:35 UTC
### Description

This should be a *good-first-issue*.

[no-this-before-super](https://eslint.org/docs/latest/rules/no-this-before-super).

**Comment by leops** [comment] 2022-12-05 08:39
Duplicate of #3481

Our planned version of this rule it tracked under the name `noUnreachableSuper`, this will probably not be its actual name though as it's not very clear. Also I don't think it qualifies as a good first issue, the reason it hasn't been implemented yet is because it relies on control flow analysis, which is a bit more complex to get right than the simpler syntax-based analysis.

**Closed by leops** 2022-12-05 08:39 UTC
Labels: task
