### ISSUE TITLE
🐛 Panic in no_catch_assign

### ISSUE THREAD

**Issue by Boshen** [rome/tools#2947] opened 2022-07-28 07:50 UTC
### Environment information

```bash
Rome CLI v"0.7.0-next.f6510d6"
```

### What happened?

This is found in [a file from the meteor repo](https://github.com/meteor/meteor/blob/devel/packages/deprecated/npm-bcrypt/wrapper.js), 

But we can have a easy minimal repro:
```
try {
} catch (e) {
  a = b;
}
```

```
Rome encountered an unexpected error

This is a bug in Rome, not an error in your code, and we would appreciate it if you could report it to https://github.com/rome/tools/issues/ along with the following information to help us fixing the issue:

Source Location: crates/rome_js_analyze/src/semantic_analyzers/js/no_catch_assign.rs:70:71
Message: called `Option::unwrap()` on a `None` value

./test.js: bug[Panic]: processing panicked: called `Option::unwrap()` on a `None` value
```

### Expected result

No panic

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by Boshen** [comment] 2022-07-28 07:52
The playground panicked with "CodeMirror plugin crashed: TypeError: Cannot read properties of null (reading 'to')"

**Comment by IWANABETHATGUY** [comment] 2022-07-28 09:02
https://play.rome.tools/?code=try+%7B%0A%7D+catch+%28e%29+%7B%0A++a+%3D+b%3B%0A%7D&lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&sourceType=module&typescript=false&jsx=false#dAByAHkAIAB7AAoAfQAgAGMAYQB0AGMAaAAgACgAZQApACAAewAKACAAIABhACAAPQAgAGIAOwAKAH0A

Can't reproduce

**Comment by Boshen** [comment] 2022-07-28 09:05
> https://play.rome.tools/?code=try+%7B%0A%7D+catch+%28e%29+%7B%0A++a+%3D+b%3B%0A%7D&lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&sourceType=module&typescript=false&jsx=false#dAByAHkAIAB7AAoAfQAgAGMAYQB0AGMAaAAgACgAZQApACAAewAKACAAIABhACAAPQAgAGIAOwAKAH0A
> 
> Can't reproduce

Please be aware of the version I'm reporting against :-), i.e. Rome CLI v"0.7.0-next.f6510d6"

**Comment by IWANABETHATGUY** [comment] 2022-07-28 09:09
This should be fixed in main branch already.
I use the latest local compiled cli can't reproduce it.

**Comment by ematipico** [comment] 2022-07-28 11:01
I can confirm that this is fixed on `main` :) 

If everything goes smoothly, next week we will release `0.8.0` with this fix. Thank you @Boshen for reporting it~

**Closed by ematipico** 2022-07-28 11:01 UTC
Labels: bug: unconfirmed
