### ISSUE TITLE
🐛 formatter break emoji sequence

### ISSUE THREAD

**Issue by dangh** [rome/tools#3915] opened 2022-12-01 14:20 UTC
### Environment information

```block
CLI:
  Version:              10.0.1
  Color support:        true

Platform:
  CPU Architecture:     aarch64
  OS:                   macos

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               loaded
  Formatter disabled:   false
  Linter disabled:      true

Workspace:
  Open Documents:       0

Discovering running Rome servers...

Server:
  Status:               stopped
```

### What happened?

Run this command:

```sh
echo '// ⚙️' | rome format --stdin-file-path test.js
```

The output is:

```
// ⚙�

```

### Expected result

The emoji should be intact:

```
// ⚙️
```

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by leops** [comment] 2022-12-06 13:26
I'm guessing this probably depends on the default encoding on your machine, the Rome CLI doesn't have a way to detect this so it reads the content of the stdin pipe as an UTF-8 encoded string, and if that's not the actual encoding of the input it may either print garbage characters or exit with an error. Unfortunately I don't have access to a Unix machine to test this further.

**Comment by MichaReiser** [comment] 2022-12-06 13:47
I'm able to reproduce the issue on linux when piping the input. The issue is that it breaks the trailing variant selector symbol. This isn't an issue when the input is read from a file.

**Comment by Gin-Quin** [comment] 2023-02-21 03:38
I don't know if this is related, but I created an issue that happens when inserting an emoji is inside a string and applying the formatter: https://github.com/rome/tools/issues/4222

**Comment by ematipico** [comment] 2023-05-08 13:49
This should be fixed

**Closed by ematipico** 2023-05-08 13:49 UTC
Labels: S-To triage
