### ISSUE TITLE
🐛 Rome invalid catch of object key name outside of defined interface scope

### ISSUE THREAD

**Issue by MrSimmmons** [rome/tools#4517] opened 2023-05-20 12:56 UTC
### Environment information

```block
CLI:
  Version:                      12.1.2
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           macos

Environment:
  ROME_LOG_DIR:                 unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v14.18.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/1.22.19"

Rome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

See [playground](https://docs.rome.tools/playground/?code=aQBuAHQAZQByAGYAYQBjAGUAIABGAG8AbwAgAHsACgAgACAAYgBhAHIAOgAgAHsACgAgACAAIAAgAFsAawBlAHkAOgAgAHMAdAByAGkAbgBnAF0AOgAgAHUAbgBrAG4AbwB3AG4AOwAKACAAIAAgACAAYgBhAHoAOgAgAG4AdQBtAGIAZQByADsACgAgACAAfQA7AAoAIAAgAGYAbwBvAEIAYQByADoAIAB7AAoAIAAgACAAIABbAGsAZQB5ADoAIABzAHQAcgBpAG4AZwBdADoAIAB1AG4AawBuAG8AdwBuADsACgAgACAAIAAgAGYAbwBvAEIAYQByAEIAYQB6ADoAIABiAG8AbwBsAGUAYQBuADsACgAgACAAfQA7AAoAfQA%3D) for example

Notice how in the playground example you can rename the second `key` to any other string and it works fine.

### Expected result

I should be able to re-declare an interface object key in a different scope using the same name without Rome triggering an error

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by MrSimmmons** [comment] 2023-05-20 12:57
Please feel free to rename the title. I'm unsure how to describe the issue in a small amount of words

**Comment by ematipico** [comment] 2023-05-20 13:03
Duplicate of https://github.com/rome/tools/issues/4478

**Closed by ematipico** 2023-05-20 13:03 UTC
Labels: S-To triage
