### ISSUE TITLE
🐛 false positive for lint/correctness/noUnusedVariables when use decorator

### ISSUE THREAD

**Issue by sikkapat79** [rome/tools#4649] opened 2023-07-03 05:01 UTC
### Environment information

```block
rome check ./src
```

### What happened?

1. I'm using version "12.1.3"
2. It's throw with false positive when imported variables is decorator.
<img width="685" alt="Screenshot 2566-07-03 at 11 54 45" src="https://github.com/rome/tools/assets/29978819/13e98999-c6c4-4f2d-951f-6f942f06dc58">

### Expected result

It should not throw error.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment] 2023-07-03 05:19
Duplicate of https://github.com/rome/tools/issues/4540

**Closed by ematipico** 2023-07-03 05:19 UTC
Labels: S-To triage
