### ISSUE TITLE
🐛 `correctness/noUnusedVariables` false positive

### ISSUE THREAD

**Issue by jpike88** [rome/tools#4449] opened 2023-05-09 08:22 UTC
### Environment information

```block
see screenshot, that variable is unused in the function it's declaring. It's also an acceptable pattern for rxjs calls.
```

### What happened?

![Screenshot 2023-05-09 at 3 20 37 pm](https://user-images.githubusercontent.com/9585787/237037838-b6c117d2-ea6f-49e7-bdf7-2a2297662f10.png)

### Expected result

it shouldn't flag that code as wrong.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment] 2023-05-09 09:01
Duplicate of https://github.com/rome/tools/issues/4245

**Closed by ematipico** 2023-05-09 09:01 UTC
Labels: S-To triage
