### ISSUE TITLE
🐛 Linter rule `noUnusedVariables` doesn't like `as const` sometimes

### ISSUE THREAD

**Issue by amatthews4851** [rome/tools#4140] opened 2023-01-05 02:40 UTC
### Environment information

```block
I added it to the comment as a txt file since my "comment was too long"
```

### What happened?

So I had an existing project and had been using Rome as its full time formatter and linter, but then I turned on `noUndeclaredVariables` and `noUnusedVariables`
```json
{
  "$schema": "./node_modules/rome/configuration_schema.json",
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true,
      "correctness": {
        "noUnusedVariables": "error",
        "noUndeclaredVariables": "error"
      }
    }
  }
}
```
and now running `yarn rome check .` and the vscode extension both give me errors of
```
The const variable is undeclared
```
everywhere I try to do something like 
```tsx
import * as React from "react";
import { useSpring } from "@react-spring/native";
import { sleep } from "utils/async";

const useSpringSwitch = (on: boolean) => {
	const { opacity } = useSpring({ opacity: on ? 1 : 0 });
	const [opacityState, setOpacityState] = React.useState(0);

	React.useEffect(() => {
		const tick = async () => {
			const newValue = opacity.get();
			setOpacityState(newValue);
			if ((on && newValue < 1) || (!on && newValue > 0)) {
				await sleep(50);
				tick();
			}
		};

		tick();
	}, [on]);

	return [opacityState, opacity] as const; // <- this right here is where I get the error
};

export default useSpringSwitch;
```
<img width="693" alt="Screenshot 2023-01-04 at 8 29 21 PM" src="https://user-images.githubusercontent.com/31320460/210687807-2ce1424c-b16a-4f37-b997-3d8be0464890.png">

But I can upload this code to the playground and it works as expected, so it seems like this is just a bug somewhere in my setup. I have tried removing and reinstalling my node_modules, and I am on version 11.0.0, which is just installed locally to my project. 

[rome_rage.txt](https://github.com/rome/tools/files/10348905/rome_rage.txt)

### Expected result

`const` should be a valid global typescript type.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment] 2023-01-06 09:23
I had a look at your rage output, and it seems you're still running an old version of the VSCode extension.

I suggest to upload it, close VSCode, kill the LSP server (via `rome stop` or using the process manager) and re open it.

If you still see the issue and you can't reproduce it in the playground (I couldn't), it means the issue is fixed on `main`.

**Comment by amatthews4851** [comment] 2023-01-06 16:11
Hmmm... I checked for updates and it said there were none. It was on `v0.20.0`. I then tried uninstalling and reinstalling, restarting the rome server, and still same thing.

I then tried switching to the prerelease version, `v0.21.20221217`, and restarting the lsp and still same thing. 

What would be the current version?

**Comment by flother** [comment] 2023-01-13 19:52
I've just ran into this too. Here's a minimal example that's reproducible on the command-line:

```sh
$ mkdir new-project
$ cd new-project
$ npm install rome
$ npx rome --version
Rome CLI version 11.0.0
$ cat > rome.json <<EOT
{
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true,
      "correctness": {
        "noUndeclaredVariables": "warn"
      }
    }
  }
}
EOT
$ echo "const a = [1, 2, 3] as const;" > index.ts
$ npx rome check index.ts
index.ts:1:24 lint/correctness/noUndeclaredVariables ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ⚠ The const variable is undeclared

  > 1 │ const a = [1, 2, 3] as const;
      │                        ^^^^^
    2 │


Checked 1 file(s) in 3ms
```

**Comment by Conaclos** [comment] 2023-02-14 18:52
This should be fixed by https://github.com/rome/tools/pull/3981

The fix will be in the incoming release.

**Closed** 2023-02-14 18:52 UTC
Labels: S-Needs info
